### ISSUE TITLE
PA Review: Notebooks

### ISSUE THREAD

**Issue by ommish** [ommish/Omninote#27]

**Comment by OscarAlvarez8830** [comment]
The dropdown list doesn't actually take me to each notebook :(

**Comment by OscarAlvarez8830** [comment]
Deletion doesn't work.

**Comment by ommish** [comment]
Do you mean selecting a new notebook from the dropdown should redirect you? It doesn't seem to do that on Evernote. It's just to select which notebook the note you are creating/editing should be saved to I think.
Notebook deletion is fixed though!

**Comment by OscarAlvarez8830** [comment]
Ohhhhhhhhhhhhhhh.

Not super clear UI.

Also I can't check any of this because Heroku died ☠️
